version: '3.7'
services:
  database_car_rent:
    image: postgres
    container_name: database_car_rent
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=car-rent
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: car-rent
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local
