import '@modules/users/providers'
import '@modules/categories/providers'
import '@modules/specifications/providers'
import '@modules/cars/providers'
import '@shared/providers'
import '@modules/rentals/providers'
